export enum WordFlow {
    // COMMUN
    REJETER = 'REJETER',
    VALIDER = 'VALIDER',
    // CONTRAT
    AVANT_PROJET = 'AVANT_PROJET',
    TRANS_SOUMISSIONNAIRE = 'TRANS_SOUMISSIONNAIRE',
    RECEPTION_CONTRAT = 'RECEPTION_CONTRAT',
    APPROUVER = 'APPROUVER',
    // ENGAGEMENT
    ENGAGEMENT = 'ENGAGEMENT',
    VISA_CONTROLEUR = 'VISA_CONTROLEUR',
    VISA_ORDONNATEUR = 'VISA_ORDONNATEUR',
    // LIQUIDATION
    CREATION_LIQUIDATION = 'CREATION_LIQUIDATION',
    VISA_LIQ_CONTROLEUR = 'VISA_LIQ_CONTROLEUR',
    VISA_LIQ_ORDONNATEUR = 'VISA_LIQ_ORDONNATEUR',
    LIQUIDER = 'LIQUIDER'
}
