version: '2'
services:
  marchepublicgateway-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/marchepublicgateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=marchepublicgateway
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
